For the third review
szimina/web-larek-express pull request #1
Opened 2024-10-06 19:16 UTC by szimina

2024-10-06 19:45 UTC, aromanovnik commented on backend/package.json
Надо исправить: При запуске команды `npm run lint` обнаружены 7 ошибок. Эти ошибки необходимо устранить

2024-10-06 19:55 UTC, aromanovnik commented on backend/src/app.ts
> +app.use('/product', productRouter);
**Можно лучше**: Лучше вынести всю логику, связанную с навигацией, в файл `routes/index.ts`, а в `app.ts` просто подключить ее, используя, например, следующую конструкцию: `app.use(routes);`. Это сделает код более структурированным, упростит поддержку и позволит сосредоточить всю логику маршрутизации в одном месте.

2024-10-06 20:01 UTC, aromanovnik commented on backend/src/models/product.ts
> +    required: [true, 'Поле title должно быть заполнено'],
**Отлично!**: Круто, что используются сообщения в случае ошибки при валидации. Это делает ответы API более информативными и значительно упрощает взаимодействие с клиентской стороной.

2024-10-06 20:20 UTC, aromanovnik commented on backend/src/routes/product.ts
> +router.post('/', createProduct);
**Надо исправить**: Согласно требованиям:  _Тела запросов к серверу должны валидироваться до передачи обработки в контроллеры. Если запрос принимает какую-то информацию в заголовках или параметрах, валидируйте и её. Для валидации используйте библиотеку `celebrate` + `joi`._ 
Например: `router.post('/', validateProductBody, createProduct);`

2024-10-06 20:25 UTC, aromanovnik commented on backend/src/contollers/products.ts
> +  const existingItem = await Product.findOne({ title });
**Можно лучше**: Эта проверка не нужна, так как уже указано, что поле title является unique. При попытке создать карточку с уже существующим заголовком будет возвращена ошибка автоматически. Дополнительный запрос к базе данных только увеличивает время ответа и снижает производительность.

2024-10-06 20:37 UTC, aromanovnik commented on backend/src/constants/errors.ts
> +export enum errorMessage400 {
**Отлично!**: что используются enum. Это действительно хорошая практика, которая повышает читаемость и поддержку кода, а также помогает избежать ошибок, связанных с “магическими” значениями.

2024-10-06 20:45 UTC, aromanovnik commented on backend/src/app.ts
> +mongoose.connect(DB_ADDRESS);
**Можно лучше**: Запуск сервера лучше осуществлять только после успешного подключения к базе данных. Нельзя стартовать сервер без активной связи с базой, так как на продакшене это может привести к немедленному падению приложения.

2024-10-06 20:59 UTC, aromanovnik requested changes
Добрый день, Светлана!

Работа выполнена очень хорошо, круто, что используются `enum` и информативные сообщения в случае ошибок при валидации. Код выглядит профессионально и структурированно. Однако есть пара моментов, которые нужно исправить.

Что нужно исправить:
* При запуске команды `npm run lint` обнаружены 7 ошибок. Эти ошибки необходимо устранить
* Согласно требованиям: _Тела запросов к серверу должны валидироваться до передачи обработки в контроллеры. Если запрос принимает какую-то информацию в заголовках или параметрах, валидируйте и её. Для валидации используйте библиотеку `celebrate` + `joi`._ Например: `router.post('/', validateProductBody, createProduct);`

Что можно улучшить:
* Запуск сервера лучше осуществлять только после успешного подключения к базе данных. Нельзя стартовать сервер без активной связи с базой, так как на продакшене это может привести к немедленному падению приложения.
* Лучше вынести всю логику, связанную с навигацией, в файл `routes/index.ts`, а в `app.ts` просто подключить ее, используя, например, следующую конструкцию: `app.use(routes);`. Это сделает код более структурированным, упростит поддержку и позволит сосредоточить всю логику маршрутизации в одном месте.
* Проверка `existingItem` не нужна, так как уже указано, что поле `title` является unique. При попытке создать карточку с уже существующим заголовком будет возвращена ошибка автоматически. Дополнительный запрос к базе данных только увеличивает время ответа и снижает производительность.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний Надо исправить.
Удачного рефакторинга кода.

2024-10-08 20:23 UTC, aromanovnik requested changes
Добрый день, Светлана!

Проделан отличный рефакторинг, критические замечания и пожелания исправлены. Но есть один момент, который я не заметил во время первого ревью. 

Надо исправить: 
* По умолчанию Express возвращает статус `200`, но при создании ресурсов по REST-стандартам нужно возвращать статус `201` (Created). Это важно для правильной семантики HTTP-запросов и лучшего взаимодействия с клиентами API.

Можно лучше: 
* Лучше оставить разделение навигации на отдельные файлы, такие как `product.ts` и `order.ts`, для лучшей модульности и читаемости. А в `index.ts` оставить только основную маршрутизацию
* Метод `delete` не входит в обязательные требования, но параметр `:id` также должен быть проверен. В этом случае, вместо использования `Segments.BODY`, нужно использовать `Segments.PARAMS`.
* Опечатка в названии директории: вместо `contollers` должно быть `controllers`. Если исправить название директории, автотесты перестанут падать с ошибкой “Отсутствует директория controllers и необходимые файлы в ней.”

Напоминаю, что работа может быть принята только после исправления всех критических замечаний Надо исправить.
Удачного рефакторинга кода.

2024-10-08 20:23 UTC, aromanovnik commented on backend/src/contollers/products.ts
> +    .then((product) => res.send({ item: product }))
**Надо исправить**: По умолчанию Express возвращает статус `200`, но при создании ресурсов по REST-стандартам нужно возвращать статус `201` (Created). Это важно для правильной семантики HTTP-запросов и лучшего взаимодействия с клиентами API.

2024-10-08 20:23 UTC, aromanovnik commented on backend/src/routes/routes.ts
> +router.delete('/product/:id', deleteProduct);
**Можно лучше**: Метод `delete` не входит в обязательные требования, но параметр `:id` также должен быть проверен. В этом случае, вместо использования `Segments.BODY`, нужно использовать `Segments.PARAMS`.

2024-10-08 20:23 UTC, aromanovnik commented on backend/src/routes/routes.ts
> +import { getProducts, createProduct, deleteProduct } from '../contollers/products';
**Можно лучше:** Опечатка в названии директории: вместо `contollers` должно быть `controllers`. Если исправить название директории, автотесты перестанут падать с ошибкой “Отсутствует директория `controllers` и необходимые файлы в ней.”

2024-10-08 20:23 UTC, aromanovnik commented on backend/src/routes/routes.ts
> +const router = Router();
**Можно лучше**: Лучше оставить разделение навигации на отдельные файлы, такие как `product.ts` и `order.ts`, для лучшей модульности и читаемости. А в `index.ts` оставить только основную маршрутизацию:

```
const router = Router();
router.use('/product', productRouter);
router.use('/order', orderRouter);
export default router;

```

2024-10-08 22:13 UTC, szimina commented on backend/src/routes/routes.ts
> +const router = Router();
Так у меня изначально так и было. Но в первом review пришел комментарий, что нужно вынести роутинг в файл routes.ts. Откатываю обратно?
![image](https://github.com/user-attachments/assets/ba2a3bbe-5256-4d58-83bc-87e98bc8dbe4)

2024-10-09 10:36 UTC, aromanovnik commented on backend/src/routes/routes.ts
> +const router = Router();
Всю навигацию правильнее держать в папке routes, разделив файлы по категориям (`product.ts`, `order.ts` и т.д.). В файле `routes/index.ts` (пример файла в комментарии выше) подключать все нужные эндпоинты и экспортировать их, чтобы в `app.ts` подключить только следующее: `app.use(routes);`. Этот подход поможет избежать засорения app.ts по мере роста проекта, а вся логика маршрутизации будет сосредоточена в папке routes, что улучшит поддержку и масштабируемость проекта.

В итоге структура папки `routes` может выглядеть так:
<img width="172" alt="Снимок экрана 2024-10-09 в 13 25 56" src="https://github.com/user-attachments/assets/4dba597f-d5e3-4577-b22f-da3ab1486335">

Напоминаю, что комментарии `Можно лучше` не обязательны к исправлению.

2024-10-09 19:27 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-10-09 19:35 UTC, merged